export { DeleteIcon } from './delete'
export { EditIcon } from './edit'
export * from './eyeOff'
export * from './eyeOn'
export * from './logo'
export * from './logout'
export * from './person'
export * from './signOut'
export * from './start.tsx'
export * from './play'
export * from './image'
export * from './star'
